//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sahand.Payaneh.Service.SendingMsgModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmsPatternResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsPatternResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sahand.Payaneh.Service.SendingMsgModule.Resources.SmsPatternResource", typeof(SmsPatternResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d847hdxktt.
        /// </summary>
        public static string BloodTestReq {
            get {
                return ResourceManager.GetString("BloodTestReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8p0w3u1fzy.
        /// </summary>
        public static string BloodTestResult {
            get {
                return ResourceManager.GetString("BloodTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tja2nkq41x.
        /// </summary>
        public static string CoachHasNewInvoice {
            get {
                return ResourceManager.GetString("CoachHasNewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hcofegibtu.
        /// </summary>
        public static string CompanyCreateUser {
            get {
                return ResourceManager.GetString("CompanyCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3blpqb033n.
        /// </summary>
        public static string DelayCoach {
            get {
                return ResourceManager.GetString("DelayCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d5olt6q5ch.
        /// </summary>
        public static string InvoiceFinish {
            get {
                return ResourceManager.GetString("InvoiceFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ebjoj3ptek.
        /// </summary>
        public static string InvoicePayment {
            get {
                return ResourceManager.GetString("InvoicePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnbhl2gnx2.
        /// </summary>
        public static string ResetPass {
            get {
                return ResourceManager.GetString("ResetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u1oz3hzfvx.
        /// </summary>
        public static string SendPasswordToDriver {
            get {
                return ResourceManager.GetString("SendPasswordToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3o0d2j044d.
        /// </summary>
        public static string VerifyUserCode {
            get {
                return ResourceManager.GetString("VerifyUserCode", resourceCulture);
            }
        }
    }
}
